In [2]:
import pandas as pd
import numpy as np 

df_phone = pd.read_csv("./phones.csv")

print(df_phone.columns)

for col in df_phone.columns:
    print(col, ":", df_phone[col].isna().mean()*100 )      # np.isnan only works when there is numerical column

Index(['phone_id', 'account_id', 'source', 'relation_recorded', 'added_date',
       'phone_masked', 'priority_slot'],
      dtype='str')
phone_id : 0.0
account_id : 0.0
source : 0.0
relation_recorded : 0.0
added_date : 0.0
phone_masked : 0.0
priority_slot : 0.0

In [3]:

df_skip_traces = pd.read_csv("./skip_traces.csv")

print(df_skip_traces.columns)

for col in df_skip_traces.columns:
    print(col, ":", df_skip_traces[col].isna().mean()*100 )      

# new_contact_point_id : 77.15404699738903

Index(['trace_id', 'account_id', 'trace_date', 'trigger_rule', 'result',
       'new_contact_point_id', 'cost_inr'],
      dtype='str')
trace_id : 0.0
account_id : 0.0
trace_date : 0.0
trigger_rule : 0.0
result : 0.0
new_contact_point_id : 77.15404699738903
cost_inr : 0.0

In [4]:

df_verified_contact_point = pd.read_csv("./verified_contact_points.csv")

print(df_verified_contact_point.columns)

for col in df_verified_contact_point.columns:
    print(col, ":", df_verified_contact_point[col].isna().mean()*100 )

Index(['phone_id', 'account_id', 'verified_status', 'verified_date'], dtype='str')
phone_id : 0.0
account_id : 0.0
verified_status : 0.0
verified_date : 0.0

In [5]:
df_verified_contact_point.head(5)

   phone_id account_id      verified_status verified_date
0  PH002454   AC000848  not_borrower_number    2026-07-02
1  PH003285   AC001229      borrower_number    2026-07-02
2  PH004656   AC001865   third_party_number    2026-07-02
3  PH003943   AC001526   third_party_number    2026-07-02
4  PH000470   AC001379   third_party_number    2026-07-02

In [6]:
df_phone.head(5)

,phone_id,account_id,source,relation_recorded,added_date,phone_masked,priority_slot
0,PH000611,AC000001,kyc_origination,self,2026-04-01,XXXXXX7289,0
1,PH000612,AC000001,bureau,self,2026-04-01,XXXXXX0099,1
2,PH000613,AC000002,kyc_origination,self,2026-04-01,XXXXXX2068,0
3,PH000581,AC000002,employer,office,2026-04-01,XXXXXX8219,1
4,PH000614,AC000002,reference,reference_mother,2026-04-01,XXXXXX5322,2

In [7]:
df_skip_traces.head(5)

,trace_id,account_id,trace_date,trigger_rule,result,new_contact_point_id,cost_inr
0,ST00001,AC000285,2026-04-13,15_consecutive_failed_contacts,new_phone_found,PH005811,87
1,ST00002,AC000276,2026-04-15,15_consecutive_failed_contacts,no_new_info,NaN,91
2,ST00003,AC001982,2026-04-18,15_consecutive_failed_contacts,no_new_info,NaN,108
3,ST00004,AC002103,2026-04-18,15_consecutive_failed_contacts,new_phone_found,PH005812,109
4,ST00005,AC002236,2026-04-19,15_consecutive_failed_contacts,no_new_info,NaN,132

SHARED DATA

In [8]:

df_accounts = pd.read_csv("./shared/accounts.csv")

print(df_accounts.columns)

for col in df_accounts.columns:
    print(col, ":", df_accounts[col].isna().mean()*100 )      

# ability_to_pay_estimate : 30.291666666666668
# salary_credit_day : 68.25

Index(['account_id', 'lender_id', 'portfolio', 'income_type', 'town_id',
       'preferred_language', 'bucket_start', 'dpd_start', 'emi_amount',
       'overdue_start', 'outstanding', 'salary_credit_day',
       'bureau_score_band', 'other_active_loans', 'paid_other_lenders_30d',
       'last_bounce_reason', 'ability_to_pay_estimate', 'prev_ptp_count',
       'prev_ptp_broken', 'dialling_arm'],
      dtype='str')
account_id : 0.0
lender_id : 0.0
portfolio : 0.0
income_type : 0.0
town_id : 0.0
preferred_language : 0.0
bucket_start : 0.0
dpd_start : 0.0
emi_amount : 0.0
overdue_start : 0.0
outstanding : 0.0
salary_credit_day : 68.25
bureau_score_band : 0.0
other_active_loans : 0.0
paid_other_lenders_30d : 0.0
last_bounce_reason : 0.0
ability_to_pay_estimate : 30.291666666666668
prev_ptp_count : 0.0
prev_ptp_broken : 0.0
dialling_arm : 0.0

In [9]:
df_addresses = pd.read_csv("./shared/addresses.csv")

print(df_addresses.columns)

for col in df_addresses.columns:
    print(col, ":", df_addresses[col].isna().mean()*100 )

Index(['address_id', 'account_id', 'address_type', 'source', 'added_date',
       'town_id', 'address_text'],
      dtype='str')
address_id : 0.0
account_id : 0.0
address_type : 0.0
source : 0.0
added_date : 0.0
town_id : 0.0
address_text : 0.0

In [10]:
df_agents = pd.read_csv("./shared/agents.csv")

print(df_agents.columns)

for col in df_agents.columns:
    print(col, ":", df_agents[col].isna().mean()*100 )      


# tenure_months : 3.3333333333333335

Index(['agent_id', 'channel', 'language_team', 'town_id', 'tenure_months',
       'shift'],
      dtype='str')
agent_id : 0.0
channel : 0.0
language_team : 0.0
town_id : 70.0
tenure_months : 3.3333333333333335
shift : 0.0

In [11]:
df_dial_attempts = pd.read_csv("./shared/dial_attempts.csv")

print(df_dial_attempts.columns)

for col in df_dial_attempts.columns:
    print(col, ":", df_dial_attempts[col].isna().mean()*100 )

# ptp_id : 93.95166813423344

Index(['attempt_id', 'account_id', 'phone_id', 'attempt_ts', 'channel',
       'agent_id', 'dialling_arm', 'selection_propensity', 'network_response',
       'ring_duration_s', 'talk_duration_s', 'hangup_by', 'disposition',
       'remark', 'ptp_id', 'has_transcript'],
      dtype='str')
attempt_id : 0.0
account_id : 0.0
phone_id : 0.0
attempt_ts : 0.0
channel : 0.0
agent_id : 0.0
dialling_arm : 0.0
selection_propensity : 0.0
network_response : 0.0
ring_duration_s : 0.0
talk_duration_s : 0.0
hangup_by : 0.0
disposition : 0.0
remark : 0.0
ptp_id : 93.95166813423344
has_transcript : 0.0

In [12]:
df_field_visits = pd.read_csv("./shared/field_visits.csv")

print(df_field_visits.columns)

for col in df_field_visits.columns:
    print(col, ":", df_field_visits[col].isna().mean()*100 )

# ptp_id : 89.15381857296522

Index(['visit_id', 'account_id', 'address_id', 'agent_id', 'visit_date',
       'start_ts', 'checkin_ts', 'checkin_x', 'checkin_y', 'gps_accuracy_m',
       'dwell_s', 'outcome', 'ptp_id', 'remark', 'photo_hash'],
      dtype='str')
visit_id : 0.0
account_id : 0.0
address_id : 0.0
agent_id : 0.0
visit_date : 0.0
start_ts : 0.0
checkin_ts : 0.0
checkin_x : 0.0
checkin_y : 0.0
gps_accuracy_m : 0.0
dwell_s : 0.0
outcome : 0.0
ptp_id : 89.15381857296522
remark : 0.0
photo_hash : 0.0

In [13]:
df_lenders = pd.read_csv("./shared/lenders.csv")

print(df_lenders.columns)

for col in df_lenders.columns:
    print(col, ":", df_lenders[col].isna().mean()*100 )

Index(['lender_id', 'lender_name', 'lender_type', 'kyc_address_format'], dtype='str')
lender_id : 0.0
lender_name : 0.0
lender_type : 0.0
kyc_address_format : 0.0

In [14]:
df_payments = pd.read_csv("./shared/payments.csv")

print(df_payments.columns)

for col in df_payments.columns:
    print(col, ":", df_payments[col].isna().mean()*100 )

Index(['payment_id', 'account_id', 'payment_ts', 'amount', 'channel'], dtype='str')
payment_id : 0.0
account_id : 0.0
payment_ts : 0.0
amount : 0.0
channel : 0.0

In [15]:
df_splits = pd.read_csv("./shared/splits.csv")

print(df_splits.columns)

for col in df_splits.columns:
    print(col, ":", df_splits[col].isna().mean()*100 )

Index(['account_id', 'split'], dtype='str')
account_id : 0.0
split : 0.0

In [16]:
df_accounts.head(5)

,account_id,lender_id,portfolio,income_type,town_id,preferred_language,bucket_start,dpd_start,emi_amount,overdue_start,outstanding,salary_credit_day,bureau_score_band,other_active_loans,paid_other_lenders_30d,last_bounce_reason,ability_to_pay_estimate,prev_ptp_count,prev_ptp_broken,dialling_arm
0,AC000001,L03,pl_salaried,salaried,T1,kanglish,61-90,81,16750.0,50250.0,737000.0,NaN,550-649,2,False,mandate_not_registered,0.76,2,0,rule_based
1,AC000002,L03,pl_salaried,salaried,T3,english,X,0,9800.0,9800.0,284200.0,5.0,650-699,2,False,insufficient_funds,0.65,0,0,rule_based
2,AC000003,L06,msme,self_employed,T2,hinglish,61-90,70,22550.0,67650.0,766700.0,NaN,300-549,2,False,insufficient_funds,0.55,2,2,rule_based
3,AC000004,L01,credit_card,self_employed,T2,hinglish,61-90,68,4450.0,13350.0,160200.0,NaN,300-549,0,False,insufficient_funds,1.00,0,0,rule_based
4,AC000005,L01,credit_card,self_employed,T2,hinglish,1-30,24,3950.0,3950.0,63200.0,NaN,300-549,3,False,insufficient_funds,NaN,3,2,rule_based

In [17]:
df_addresses.head(5)

,address_id,account_id,address_type,source,added_date,town_id,address_text
0,AD000001,AC000001,residence,kyc_origination,2026-04-01,T1,"6th Cross, 5th Main, ಚರ್ಚ್ ಹತ್ತಿರ, Kuvempu Lay..."
1,AD000002,AC000001,office,kyc_origination,2026-04-01,T1,no. 173 12th cross 3rd main shanthi nagar kave...
2,AD000003,AC000002,residence,kyc_origination,2026-04-01,T3,367/3 e block 2nd road green park layt navanag...
3,AD000004,AC000003,residence,kyc_origination,2026-04-01,T2,#81 gali 10 ganesh mandir ke bagal mein krishn...
4,AD000005,AC000004,residence,kyc_origination,2026-04-01,T2,"behind PDS Shop, Shivaji Nagar, Devgarh Nagar ..."

In [18]:
df_agents.head(5)

  agent_id channel language_team town_id  tenure_months shift
0    TA001    tele      hinglish     NaN           23.0   day
1    TA002    tele      hinglish     NaN           54.0   day
2    TA003    tele      kanglish     NaN           18.0   day
3    TA004    tele      kanglish     NaN           27.0   day
4    TA005    tele      hinglish     NaN           34.0   day

In [19]:
df_dial_attempts.head(5)

,attempt_id,account_id,phone_id,attempt_ts,channel,agent_id,dialling_arm,selection_propensity,network_response,ring_duration_s,talk_duration_s,hangup_by,disposition,remark,ptp_id,has_transcript
0,AT0000001,AC000003,PH000615,2026-04-01 09:48:09,tele_agent,TA005,rule_based,1.0,ring_no_answer,45,0,network,no_answer,"ring hua, uthaya nahi",NaN,False
1,AT0000002,AC000006,PH000622,2026-04-01 11:40:33,voice_bot,BOT01,rule_based,1.0,ring_no_answer,28,0,network,no_answer,bot: RNR,NaN,False
2,AT0000003,AC000008,PH000627,2026-04-01 10:51:28,voice_bot,BOT01,rule_based,1.0,ring_no_answer,43,0,network,no_answer,bot: RNR,NaN,False
3,AT0000004,AC000012,PH000637,2026-04-01 10:36:20,voice_bot,BOT01,rule_based,1.0,ring_no_answer,43,0,network,no_answer,"bot: ringing, no response",NaN,False
4,AT0000005,AC000013,PH000639,2026-04-01 10:56:12,tele_agent,TA004,random_contact_point,1.0,ring_no_answer,41,0,network,no_answer,ringing no response,NaN,False

In [20]:
df_field_visits.head(5)

,visit_id,account_id,address_id,agent_id,visit_date,start_ts,checkin_ts,checkin_x,checkin_y,gps_accuracy_m,dwell_s,outcome,ptp_id,remark,photo_hash
0,VS000001,AC000652,AD000840,FA003,2026-04-01,2026-04-01 10:21:26,2026-04-01 11:00:13,1409.8,-1495.1,11.7,65,address_not_traceable,NaN,address sikkilla,cc10046a2da9
1,VS000002,AC000953,AD001233,FA003,2026-04-01,2026-04-01 11:03:48,2026-04-01 11:26:18,2517.3,-2363.0,21.1,1168,cash_collected,NaN,"1,77,600 cash collect",bf97dd9bc787
2,VS000003,AC001472,AD001899,FA003,2026-04-01,2026-04-01 11:51:40,2026-04-01 12:03:19,3016.5,-2614.8,16.5,173,locked_premises,NaN,"yaaru illa, beega haakide; nija mane Milk Dair...",adfd601e707a
3,VS000004,AC000608,AD000785,FA003,2026-04-01,2026-04-01 12:11:54,2026-04-01 12:34:04,1617.3,-1579.5,6.9,51,address_not_traceable,NaN,"address sikkilla, tumba hudukide",3b8f582aed8f
4,VS000005,AC000918,AD001186,FA003,2026-04-01,2026-04-01 12:39:52,2026-04-01 12:51:47,2864.1,-2032.0,6.2,291,met_family,NaN,"avara hendathi sikkidru, kelsakke hogidaare an...",e8cec7c70d63

In [21]:
df_lenders.head(5)

  lender_id lender_name   lender_type kyc_address_format
0       L01    Lender A  Private bank          kyc_mixed
1       L02    Lender B          NBFC          kyc_upper
2       L03    Lender C  Fintech NBFC      app_free_text
3       L04    Lender D      NBFC-MFI          kyc_mixed
4       L05    Lender E   NBFC (MSME)          kyc_upper

In [22]:
df_payments.head(5)

  payment_id account_id           payment_ts   amount         channel
0  PY0000001   AC000457  2026-04-01 19:57:52   3800.0     branch_cash
1  PY0000002   AC000067  2026-04-01 13:50:03  38700.0  nach_represent
2  PY0000003   AC000106  2026-04-01 15:54:08   2350.0            neft
3  PY0000004   AC000468  2026-04-01 19:21:32   3450.0  nach_represent
4  PY0000005   AC000471  2026-04-01 20:25:12  31600.0            bbps

In [23]:
df_splits.head(5)

  account_id  split
0   AC000001  train
1   AC000002  train
2   AC000003  train
3   AC000004  train
4   AC000005  train

In [24]:
print("PHONES:", df_phone.shape)
print("VERIFIED CONTACT POINTS:", df_verified_contact_point.shape)
print("ACCOUNTS:", df_accounts.shape)
print("DIAL ATTEMPTS:", df_dial_attempts.shape)
print("FIELD VISITS:", df_field_visits.shape)
print("SKIP TRACES:", df_skip_traces.shape)
print("ADDRESSES:", df_addresses.shape)
print("PAYMENTS:", df_payments.shape)
print("AGENTS:", df_agents.shape)
print("LENDERS:", df_lenders.shape)
print("SPLITS:", df_splits.shape)

PHONES: (5719, 7)
VERIFIED CONTACT POINTS: (250, 4)
ACCOUNTS: (2400, 20)
DIAL ATTEMPTS: (51105, 16)
FIELD VISITS: (5578, 15)
SKIP TRACES: (766, 7)
ADDRESSES: (3117, 7)
PAYMENTS: (2162, 5)
AGENTS: (30, 6)
LENDERS: (6, 4)
SPLITS: (2400, 2)

relationships between tables are valid

In [25]:
print("Phones -> accounts")
print(
    "Phones with account present:",
    df_phone["account_id"].isin(df_accounts["account_id"]).mean() * 100,
    "%"
)

print("\nVerified contacts -> phones")
print(
    "Verified rows with phone present:",
    df_verified_contact_point["phone_id"].isin(df_phone["phone_id"]).mean() * 100,
    "%"
)

print("\nDial attempts -> phones")
print(
    "Attempts with phone present:",
    df_dial_attempts["phone_id"].isin(df_phone["phone_id"]).mean() * 100,
    "%"
)

print("\nDial attempts -> accounts")
print(
    "Attempts with account present:",
    df_dial_attempts["account_id"].isin(df_accounts["account_id"]).mean() * 100,
    "%"
)

print("\nField visits -> addresses")
print(
    "Visits with address present:",
    df_field_visits["address_id"].isin(df_addresses["address_id"]).mean() * 100,
    "%"
)

Phones -> accounts
Phones with account present: 100.0 %

Verified contacts -> phones
Verified rows with phone present: 100.0 %

Dial attempts -> phones
Attempts with phone present: 100.0 %

Dial attempts -> accounts
Attempts with account present: 100.0 %

Field visits -> addresses
Visits with address present: 100.0 %

In [26]:
print("VERIFIED STATUS VALUES")
print(df_verified_contact_point["verified_status"].value_counts(dropna=False))
print("\nVERIFIED STATUS PERCENTAGES")
print(
    df_verified_contact_point["verified_status"]
    .value_counts(normalize=True, dropna=False)
    .mul(100)
    .round(2)
)

VERIFIED STATUS VALUES
verified_status
borrower_number        127
third_party_number      74
not_borrower_number     27
switched_off            19
invalid_number           3
Name: count, dtype: int64

VERIFIED STATUS PERCENTAGES
verified_status
borrower_number        50.8
third_party_number     29.6
not_borrower_number    10.8
switched_off            7.6
invalid_number          1.2
Name: proportion, dtype: float64

In [27]:
print("NETWORK RESPONSE")
print(df_dial_attempts["network_response"].value_counts(dropna=False))

print("\nDISPOSITION")
print(df_dial_attempts["disposition"].value_counts(dropna=False))

print("\nHANGUP BY")
print(df_dial_attempts["hangup_by"].value_counts(dropna=False))

print("\nCHANNEL")
print(df_dial_attempts["channel"].value_counts(dropna=False))

print("\nDIALLING ARM")
print(df_dial_attempts["dialling_arm"].value_counts(dropna=False))

NETWORK RESPONSE
network_response
ring_no_answer           24613
answered                 13303
busy_rejected             5411
not_reachable             4354
switched_off              3336
number_does_not_exist       88
Name: count, dtype: int64

DISPOSITION
disposition
no_answer              24591
call_rejected           5409
not_reachable           4354
third_party_contact     3537
switched_off            3336
rpc_ptp                 2937
rpc_hung_up             2229
rpc_call_back           1674
wrong_number            1192
rpc_refused             1049
rpc_hardship             237
third_party_ptp          154
rpc_dispute              139
rpc_claims_paid          135
invalid_number            88
language_barrier          44
Name: count, dtype: int64

HANGUP BY
hangup_by
network     32391
customer    11392
agent        7322
Name: count, dtype: int64

CHANNEL
channel
tele_agent    47344
voice_bot      3761
Name: count, dtype: int64

DIALLING ARM
dialling_arm
rule_based              48339
random_contact_point     2766
Name: count, dtype: int64

In [28]:
for value in df_dial_attempts["network_response"].unique():
    print(value, ":")
    print(df_dial_attempts[df_dial_attempts["network_response"] == value]["disposition"].value_counts(dropna=False))
    print(" ")

ring_no_answer :
disposition
no_answer    24591
rpc_ptp         22
Name: count, dtype: int64

switched_off :
disposition
switched_off    3336
Name: count, dtype: int64

answered :
disposition
third_party_contact    3537
rpc_ptp                2913
rpc_hung_up            2229
rpc_call_back          1674
wrong_number           1192
rpc_refused            1049
rpc_hardship            237
third_party_ptp         154
rpc_dispute             139
rpc_claims_paid         135
language_barrier         44
Name: count, dtype: int64

not_reachable :
disposition
not_reachable    4354
Name: count, dtype: int64

busy_rejected :
disposition
call_rejected    5409
rpc_ptp             2
Name: count, dtype: int64

number_does_not_exist :
disposition
invalid_number    88
Name: count, dtype: int64

In [29]:
response_disposition = pd.crosstab(
    df_dial_attempts["network_response"],
    df_dial_attempts["disposition"],
    margins=True
)

print(response_disposition)

response_disposition_pct = pd.crosstab(
    df_dial_attempts["network_response"],
    df_dial_attempts["disposition"],
    normalize="index"
).mul(100).round(2)

print(response_disposition_pct)

disposition            call_rejected  invalid_number  language_barrier  \
network_response
answered                           0               0                44
busy_rejected                   5409               0                 0
not_reachable                      0               0                 0
number_does_not_exist              0              88                 0
ring_no_answer                     0               0                 0
switched_off                       0               0                 0
All                             5409              88                44

disposition            no_answer  not_reachable  rpc_call_back  \
network_response
answered                       0              0           1674
busy_rejected                  0              0              0
not_reachable                  0           4354              0
number_does_not_exist          0              0              0
ring_no_answer             24591              0              0
switched_off                   0              0              0
All                        24591           4354           1674

disposition            rpc_claims_paid  rpc_dispute  rpc_hardship  \
network_response
answered                           135          139           237
busy_rejected                        0            0             0
not_reachable                        0            0             0
number_does_not_exist                0            0             0
ring_no_answer                       0            0             0
switched_off                         0            0             0
All                                135          139           237

disposition            rpc_hung_up  rpc_ptp  rpc_refused  switched_off  \
network_response
answered                      2229     2913         1049             0
busy_rejected                    0        2            0             0
not_reachable                    0        0            0             0
number_does_not_exist            0        0            0             0
ring_no_answer                   0       22            0             0
switched_off                     0        0            0          3336
All                           2229     2937         1049          3336

disposition            third_party_contact  third_party_ptp  wrong_number  \
network_response
answered                              3537              154          1192
busy_rejected                            0                0             0
not_reachable                            0                0             0
number_does_not_exist                    0                0             0
ring_no_answer                           0                0             0
switched_off                             0                0             0
All                                   3537              154          1192

disposition              All
network_response
answered               13303
busy_rejected           5411
not_reachable           4354
number_does_not_exist     88
ring_no_answer         24613
switched_off            3336
All                    51105
disposition            call_rejected  invalid_number  language_barrier  \
network_response
answered                        0.00             0.0              0.33
busy_rejected                  99.96             0.0              0.00
not_reachable                   0.00             0.0              0.00
number_does_not_exist           0.00           100.0              0.00
ring_no_answer                  0.00             0.0              0.00
switched_off                    0.00             0.0              0.00

disposition            no_answer  not_reachable  rpc_call_back  \
network_response
answered                    0.00            0.0          12.58
busy_rejected               0.00            0.0           0.00
not_reachable               0.00          100.0           0.00
number_does_not_exist       0.00            0.0           0.00
ring_no_answer             99.91            0.0           0.00
switched_off                0.00            0.0           0.00

disposition            rpc_claims_paid  rpc_dispute  rpc_hardship  \
network_response
answered                          1.01         1.04          1.78
busy_rejected                     0.00         0.00          0.00
not_reachable                     0.00         0.00          0.00
number_does_not_exist             0.00         0.00          0.00
ring_no_answer                    0.00         0.00          0.00
switched_off                      0.00         0.00          0.00

disposition            rpc_hung_up  rpc_ptp  rpc_refused  switched_off  \
network_response
answered                     16.76    21.90         7.89           0.0
busy_rejected                 0.00     0.04         0.00           0.0
not_reachable                 0.00     0.00         0.00           0.0
number_does_not_exist         0.00     0.00         0.00           0.0
ring_no_answer                0.00     0.09         0.00           0.0
switched_off                  0.00     0.00         0.00         100.0

disposition            third_party_contact  third_party_ptp  wrong_number
network_response
answered                             26.59             1.16          8.96
busy_rejected                         0.00             0.00          0.00
not_reachable                         0.00             0.00          0.00
number_does_not_exist                 0.00             0.00          0.00
ring_no_answer                        0.00             0.00          0.00
switched_off                          0.00             0.00          0.00

In [30]:
print("Number of unique remarks:")
print(df_dial_attempts["remark"].nunique())

print(
    df_dial_attempts["remark"]
    .value_counts(dropna=False)
    .head(30)
)


print(
    df_dial_attempts["remark"]
    .dropna()
    .sample(
        min(30, df_dial_attempts["remark"].notna().sum()),
        random_state=42
    )
    .to_string(index=False)
)

Number of unique remarks:
2768
remark
RNR                                         6564
ringing no response                         4532
ring ho raha hai, koi pick nahi kar raha    2653
ring hua, uthaya nahi                       2650
ring aaytu, yaaru pick maadilla             1848
not reachable                               1476
ringing, no response                        1468
no answer                                   1466
out of coverage                             1055
busy bataya                                  809
2 ring ke baad disconnect                    767
call cut kar diya                            766
call cut maadidru                            647
network nahi hai                             641
busy antha barthide                          640
bot: no answer                               619
bot: RNR                                     603
bot: ringing, no response                    570
maatu madhyadalli call cut                   510
beech mein phone kaat diya                   487
call rejected                                480
baat karte karte call kaat diya              469
network illa                                 466
disconnected after 2 rings                   463
phone off                                    436
hung up mid call                             384
shaam ko call back                           379
number switch off aa raha hai                366
baad mein call karne bola                    351
number band hai 2 mahine se                  350
Name: count, dtype: int64
      father ne uthaya, message de denge
                     ringing no response
ring ho raha hai, koi pick nahi kar raha
         number off ide eradu tnigalinda
               2 ring ek baad disconnect
                                     RNR
                 bot: dispute on charges
                           call rejected
                               no answer
                                     RNR
                                     RNR
                     ringing no response
                       call cut kar diya
ring ho raha hai, koi pick nahi kar raha
                     ringing no response
                               no answer
                  switcehd off for weeks
                   ring hua, uthaya nahi
                                     RNR
                   ring hua, uthaya nahi
                           not reachable
bot: brother answered, will pass message
                                     RNR
ring ho raha hai, koi pick nahi kar raha
                          switch off ide
               bot: ringing, no response
                                     RNR
                                     RNR
                                     RNR
                     ringing no response

In [31]:
attempts_per_phone = (
    df_dial_attempts
    .groupby("phone_id")
    .size()
)

print("Total unique phones with at least one attempt:", attempts_per_phone.shape[0])

print("\nAttempts per phone:")
print(attempts_per_phone.describe())

Total unique phones with at least one attempt: 4008

Attempts per phone:
count    4008.000000
mean       12.750749
std         8.606386
min         1.000000
25%         7.000000
50%        10.000000
75%        18.000000
max        57.000000
dtype: float64

In [32]:
print("\nNumber of phones by attempt count:")
print(
    attempts_per_phone
    .value_counts()
    .sort_index()
    .head(30)
)

Number of phones by attempt count:
1     114
2     188
3     159
4     136
5     165
6     126
7     159
8     689
9     174
10    152
11    126
12    154
13    140
14    106
15    138
16    175
17     96
18     95
19     94
20     89
21     89
22     70
23     66
24     74
25     60
26     41
27     44
28     37
29     36
30     27
Name: count, dtype: int64

never tested phone

In [33]:
all_phones = set(df_phone["phone_id"])
tested_phones = set(df_dial_attempts["phone_id"])

untested_phones = all_phones - tested_phones

print("Total phones:", len(all_phones))
print("Tested phones:", len(tested_phones))
print("Never tested phones:", len(untested_phones))

print(
    "Percentage never tested:",
    len(untested_phones) / len(all_phones) * 100
)

Total phones: 5618
Tested phones: 4008
Never tested phones: 1610
Percentage never tested: 28.657885368458523

verified phone were tested

In [34]:
verified_test_status = df_verified_contact_point.copy()

verified_test_status["was_tested"] = (
    verified_test_status["phone_id"]
    .isin(df_dial_attempts["phone_id"])
)

print(
    pd.crosstab(
        verified_test_status["verified_status"],
        verified_test_status["was_tested"]
    )
)

print(
    pd.crosstab(
        verified_test_status["verified_status"],
        verified_test_status["was_tested"],
        normalize="index"
    ).mul(100).round(2)
)

was_tested           False  True
verified_status
borrower_number         20    107
invalid_number           2      1
not_borrower_number      9     18
switched_off             1     18
third_party_number      34     40
was_tested           False  True
verified_status
borrower_number      15.75  84.25
invalid_number       66.67  33.33
not_borrower_number  33.33  66.67
switched_off          5.26  94.74
third_party_number   45.95  54.05

shared phone numbers

In [35]:
accounts_per_phone = (
    df_phone
    .groupby("phone_id")["account_id"]
    .nunique()
)

print(accounts_per_phone.describe())

count    5618.000000
mean        1.017978
std         0.172522
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         5.000000
Name: account_id, dtype: float64

In [36]:
print(
    "Phones shared by 2 or more accounts:",
    (accounts_per_phone >= 2).sum()
)

print(
    "Phones shared by 3 or more accounts:",
    (accounts_per_phone >= 3).sum()
)

print(
    "Maximum accounts sharing one phone:",
    accounts_per_phone.max()
)

Phones shared by 2 or more accounts: 74
Phones shared by 3 or more accounts: 21
Maximum accounts sharing one phone: 5

most shared phones

In [37]:
print(
    accounts_per_phone
    .sort_values(ascending=False)
    .head(20)
)

phone_id
PH000546    5
PH000295    4
PH000437    4
PH000443    4
PH000263    4
PH000283    3
PH000464    3
PH000286    3
PH000413    3
PH000581    3
PH000332    3
PH000308    3
PH000143    3
PH000324    3
PH000476    3
PH000499    3
PH000513    3
PH000341    3
PH000432    3
PH000486    3
Name: account_id, dtype: int64

relation/source of phone numbers

In [38]:
print("PHONE SOURCES")
print(df_phone["source"].value_counts())

print("\nRELATION RECORDED")
print(df_phone["relation_recorded"].value_counts())

print("\nPRIORITY SLOT")
print(df_phone["priority_slot"].value_counts().sort_index())

PHONE SOURCES
source
kyc_origination    2400
reference          1284
borrower_update     870
bureau              714
employer            303
skip_trace          148
Name: count, dtype: int64

RELATION RECORDED
relation_recorded
self                 4132
reference_spouse      450
office                303
reference_brother     251
reference_father      240
reference_friend      212
reference_mother      131
Name: count, dtype: int64

PRIORITY SLOT
priority_slot
0    2400
1    1994
2    1037
3     264
4      23
5       1
Name: count, dtype: int64

the combination

In [39]:
print(
    pd.crosstab(
        df_phone["source"],
        df_phone["relation_recorded"]
    )
)

relation_recorded  office  reference_brother  reference_father  \
source
borrower_update         0                  0                 0
bureau                  0                  0                 0
employer              303                  0                 0
kyc_origination         0                  0                 0
reference               0                251               240
skip_trace              0                  0                 0

relation_recorded  reference_friend  reference_mother  reference_spouse  self
source
borrower_update                   0                 0                 0   870
bureau                            0                 0                 0   714
employer                          0                 0                 0     0
kyc_origination                   0                 0                 0  2400
reference                       212               131               450     0
skip_trace                        0                 0                 0   148

the age of phones

In [40]:
df_phone["added_date"] = pd.to_datetime(
    df_phone["added_date"],
    errors="coerce"
)

df_dial_attempts["attempt_ts"] = pd.to_datetime(
    df_dial_attempts["attempt_ts"],
    errors="coerce"
)

df_verified_contact_point["verified_date"] = pd.to_datetime(
    df_verified_contact_point["verified_date"],
    errors="coerce"
)

inspect the date ranges

In [41]:
print("Phone added date:")
print(df_phone["added_date"].min(), "to", df_phone["added_date"].max())

print("\nAttempt date:")
print(df_dial_attempts["attempt_ts"].min(), "to", df_dial_attempts["attempt_ts"].max())

print("\nVerified date:")
print(
    df_verified_contact_point["verified_date"].min(),
    "to",
    df_verified_contact_point["verified_date"].max()
)

Phone added date:
2026-04-01 00:00:00 to 2026-06-29 00:00:00

Attempt date:
2026-04-01 08:01:00 to 2026-06-29 18:54:35

Verified date:
2026-07-02 00:00:00 to 2026-07-02 00:00:00

Inspect calling behaviour by hour

In [42]:
df_dial_attempts["attempt_hour"] = (
    df_dial_attempts["attempt_ts"].dt.hour
)

print(
    df_dial_attempts["attempt_hour"]
    .value_counts()
    .sort_index()
)

attempt_hour
8     7650
9     7623
10    7694
11    7673
12    7675
13    2182
14    2134
15    2080
16    2136
17    2126
18    2132
Name: count, dtype: int64

talktime per hour

In [43]:
hour_summary = (
    df_dial_attempts
    .groupby("attempt_hour")
    .agg(
        attempts=("attempt_id", "count"),
        avg_ring=("ring_duration_s", "mean"),
        avg_talk=("talk_duration_s", "mean")
    )
)

print(hour_summary)

              attempts   avg_ring   avg_talk
attempt_hour
8                 7650  19.990065  40.461699
9                 7623  20.587039  37.269972
10                7694  21.738108  30.893943
11                7673  21.603545  27.985273
12                7675  21.907752  28.405733
13                2182  21.972502  32.720440
14                2134  20.956420  31.001406
15                2080  21.639423  28.803365
16                2136  20.794476  27.247659
17                2126  21.402634  35.524459
18                2132  20.381332  38.568480

bias / exploration data

In [44]:
print("DIALLING ARM")
print(df_dial_attempts["dialling_arm"].value_counts())

print("\nSELECTION PROPENSITY SUMMARY")
print(df_dial_attempts["selection_propensity"].describe())

DIALLING ARM
dialling_arm
rule_based              48339
random_contact_point     2766
Name: count, dtype: int64

SELECTION PROPENSITY SUMMARY
count    51105.000000
mean         0.976672
std          0.116166
min          0.250000
25%          1.000000
50%          1.000000
75%          1.000000
max          1.000000
Name: selection_propensity, dtype: float64

In [45]:
print("\nSelection propensity by dialling arm")

print(
    df_dial_attempts
    .groupby("dialling_arm")["selection_propensity"]
    .describe()
)

Selection propensity by dialling arm
                        count      mean       std   min     25%  50%  75%  max
dialling_arm
random_contact_point   2766.0  0.568984  0.271345  0.25  0.3333  0.5  1.0  1.0
rule_based            48339.0  1.000000  0.000000  1.00  1.0000  1.0  1.0  1.0

In [46]:
print("\nSelection propensity unique values:")
print(
    df_dial_attempts["selection_propensity"]
    .value_counts()
    .sort_index()
    .head(50)
)

Selection propensity unique values:
selection_propensity
0.2500      234
0.3333      697
0.5000     1104
1.0000    49070
Name: count, dtype: int64

Compare rule-based vs random contact selection

In [47]:
arm_outcome = pd.crosstab(
    df_dial_attempts["dialling_arm"],
    df_dial_attempts["disposition"],
    normalize="index"
).mul(100).round(2)

print(arm_outcome)

disposition           call_rejected  invalid_number  language_barrier  \
dialling_arm
random_contact_point           9.07            0.14              0.14
rule_based                    10.67            0.17              0.08

disposition           no_answer  not_reachable  rpc_call_back  \
dialling_arm
random_contact_point      45.08           8.53           3.29
rule_based                48.29           8.52           3.27

disposition           rpc_claims_paid  rpc_dispute  rpc_hardship  rpc_hung_up  \
dialling_arm
random_contact_point             0.25         0.22          0.33         3.29
rule_based                       0.26         0.28          0.47         4.42

disposition           rpc_ptp  rpc_refused  switched_off  third_party_contact  \
dialling_arm
random_contact_point     4.48         1.59          7.66                12.11
rule_based               5.82         2.08          6.46                 6.62

disposition           third_party_ptp  wrong_number
dialling_arm
random_contact_point             0.61          3.18
rule_based                       0.28          2.28

In [48]:
arm_network = pd.crosstab(
    df_dial_attempts["dialling_arm"],
    df_dial_attempts["network_response"],
    normalize="index"
).mul(100).round(2)

print(arm_network)

network_response      answered  busy_rejected  not_reachable  \
dialling_arm
random_contact_point     29.50           9.07           8.53
rule_based               25.83          10.67           8.52

network_response      number_does_not_exist  ring_no_answer  switched_off
dialling_arm
random_contact_point                   0.14           45.08          7.66
rule_based                             0.17           48.34          6.46

field-visit outcomes

In [49]:
print("FIELD VISIT OUTCOMES")
print(df_field_visits["outcome"].value_counts())

print("\nFIELD VISIT OUTCOME PERCENTAGES")
print(
    df_field_visits["outcome"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

FIELD VISIT OUTCOMES
outcome
address_not_traceable     1400
locked_premises           1249
met_borrower              1114
met_family                1062
neighbour_says_shifted     455
no_such_person             206
cash_collected              92
Name: count, dtype: int64

FIELD VISIT OUTCOME PERCENTAGES
outcome
address_not_traceable     25.10
locked_premises           22.39
met_borrower              19.97
met_family                19.04
neighbour_says_shifted     8.16
no_such_person             3.69
cash_collected             1.65
Name: proportion, dtype: float64

In [50]:
print("\nUnique field visit outcomes:")
print(df_field_visits["outcome"].unique())

Unique field visit outcomes:
<StringArray>
[ 'address_not_traceable',         'cash_collected',        'locked_premises',
             'met_family',           'met_borrower',         'no_such_person',
 'neighbour_says_shifted']
Length: 7, dtype: str

skip-trace results

In [51]:
print("SKIP TRACE RESULTS")
print(df_skip_traces["result"].value_counts())

print("\nSKIP TRACE TRIGGERS")
print(df_skip_traces["trigger_rule"].value_counts())

SKIP TRACE RESULTS
result
no_new_info          591
new_phone_found      148
new_address_found     27
Name: count, dtype: int64

SKIP TRACE TRIGGERS
trigger_rule
15_consecutive_failed_contacts    766
Name: count, dtype: int64

In [52]:
trace_success = pd.crosstab(
    df_skip_traces["trigger_rule"],
    df_skip_traces["result"],
    normalize="index"
).mul(100).round(2)

print(trace_success)

result                          new_address_found  new_phone_found  \
trigger_rule
15_consecutive_failed_contacts               3.52            19.32

result                          no_new_info
trigger_rule
15_consecutive_failed_contacts        77.15

successful contact tend to precede payment?

In [53]:
df_payments["payment_ts"] = pd.to_datetime(
    df_payments["payment_ts"],
    errors="coerce"
)

In [54]:
rpc_candidates = df_dial_attempts[
    df_dial_attempts["disposition"]
    .astype(str)
    .str.contains("right|rpc|borrower", case=False, regex=True)
]

print("Possible RPC-related disposition rows:")
print(rpc_candidates.shape[0])

print(
    rpc_candidates["disposition"].value_counts()
)

Possible RPC-related disposition rows:
8400
disposition
rpc_ptp            2937
rpc_hung_up        2229
rpc_call_back      1674
rpc_refused        1049
rpc_hardship        237
rpc_dispute         139
rpc_claims_paid     135
Name: count, dtype: int64

actual verified_status against call outcomes

In [55]:
phone_status = df_verified_contact_point[
    ["phone_id", "account_id", "verified_status", "verified_date"]
].copy()

attempt_status = df_dial_attempts.merge(
    phone_status,
    on=["phone_id", "account_id"],
    how="inner"
)

print("Attempts matched to verified status:", len(attempt_status))

print(
    pd.crosstab(
        attempt_status["verified_status"],
        attempt_status["disposition"],
        margins=True
    )
)

Attempts matched to verified status: 2189
disposition          call_rejected  invalid_number  no_answer  not_reachable  \
verified_status
borrower_number                221               0        768             80
invalid_number                   0               2          0              0
not_borrower_number              4               0         49             19
switched_off                    10               0         31             61
third_party_number              20               0        164             25
All                            255               2       1012            185

disposition          rpc_call_back  rpc_claims_paid  rpc_dispute  \
verified_status
borrower_number                 73                6            8
invalid_number                   0                0            0
not_borrower_number              5                0            1
switched_off                     2                0            0
third_party_number              12                0            0
All                             92                6            9

disposition          rpc_hardship  rpc_hung_up  rpc_ptp  rpc_refused  \
verified_status
borrower_number                12           97      119           34
invalid_number                  0            0        0            0
not_borrower_number             0            2        3            3
switched_off                    0            3        2            0
third_party_number              0            0        7            1
All                            12          102      131           38

disposition          switched_off  third_party_contact  third_party_ptp  \
verified_status
borrower_number                11                   22                3
invalid_number                  0                    0                0
not_borrower_number            39                    6                0
switched_off                   89                    1                0
third_party_number              8                  121                4
All                           147                  150                7

disposition          wrong_number   All
verified_status
borrower_number                10  1464
invalid_number                  0     2
not_borrower_number            19   150
switched_off                    1   200
third_party_number             11   373
All                            41  2189

In [56]:
print(
    pd.crosstab(
        attempt_status["verified_status"],
        attempt_status["network_response"],
        margins=True
    )
)

network_response     answered  busy_rejected  not_reachable  \
verified_status
borrower_number           383            221             80
invalid_number              0              0              0
not_borrower_number        38              4             19
switched_off                9             10             61
third_party_number        156             20             25
All                       586            255            185

network_response     number_does_not_exist  ring_no_answer  switched_off   All
verified_status
borrower_number                          0             769            11  1464
invalid_number                           2               0             0     2
not_borrower_number                      0              50            39   150
switched_off                             0              31            89   200
third_party_number                       0             164             8   373
All                                      2            1014           147  2189

In [57]:
print("ACCOUNT SPLIT")
print(df_splits["split"].value_counts())

print("\nAccount split percentages")
print(
    df_splits["split"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

ACCOUNT SPLIT
split
train         1680
validation     360
test           360
Name: count, dtype: int64

Account split percentages
split
train         70.0
validation    15.0
test          15.0
Name: proportion, dtype: float64

In [58]:
print("\nAccounts by split and dialling arm")

account_arm = df_accounts.merge(
    df_splits,
    on="account_id",
    how="left"
)

print(
    pd.crosstab(
        account_arm["split"],
        account_arm["dialling_arm"]
    )
)

Accounts by split and dialling arm
dialling_arm  random_contact_point  rule_based
split
test                            14         346
train                           89        1591
validation                      20         340

whether phone IDs are unique within accounts

In [59]:
phone_duplicates = (
    df_phone
    .groupby(["phone_id", "account_id"])
    .size()
)

print("Duplicate phone_id-account_id pairs:")
print((phone_duplicates > 1).sum())

Duplicate phone_id-account_id pairs:
0

In [60]:
print("\nPhones per account")

phones_per_account = (
    df_phone
    .groupby("account_id")["phone_id"]
    .nunique()
)

print(phones_per_account.describe())

print("\nDistribution:")
print(
    phones_per_account
    .value_counts()
    .sort_index()
)

Phones per account
count    2400.000000
mean        2.382917
std         0.914224
min         1.000000
25%         2.000000
50%         2.000000
75%         3.000000
max         6.000000
Name: phone_id, dtype: float64

Distribution:
phone_id
1    406
2    957
3    773
4    241
5     22
6      1
Name: count, dtype: int64

raw RPC outcome temporarily

In [61]:
rpc_dispositions = [
    "rpc_ptp",
    "rpc_hung_up",
    "rpc_call_back",
    "rpc_refused",
    "rpc_hardship",
    "rpc_dispute",
    "rpc_claims_paid"
]

df_dial_attempts["is_rpc"] = (
    df_dial_attempts["disposition"]
    .isin(rpc_dispositions)
)

print("RPC attempts:", df_dial_attempts["is_rpc"].sum())
print(
    "RPC rate:",
    df_dial_attempts["is_rpc"].mean() * 100
)

RPC attempts: 8400
RPC rate: 16.436747872028175

non-RPC outcomes

In [62]:
non_rpc_summary = (
    df_dial_attempts
    .groupby("disposition")
    .agg(
        attempts=("attempt_id", "count"),
        rpc_rate=("is_rpc", "mean")
    )
    .sort_values("attempts", ascending=False)
)

non_rpc_summary["percentage"] = (
    non_rpc_summary["attempts"]
    / len(df_dial_attempts)
    * 100
)

print(non_rpc_summary.round(3))

                     attempts  rpc_rate  percentage
disposition
no_answer               24591       0.0      48.119
call_rejected            5409       0.0      10.584
not_reachable            4354       0.0       8.520
third_party_contact      3537       0.0       6.921
switched_off             3336       0.0       6.528
rpc_ptp                  2937       1.0       5.747
rpc_hung_up              2229       1.0       4.362
rpc_call_back            1674       1.0       3.276
wrong_number             1192       0.0       2.332
rpc_refused              1049       1.0       2.053
rpc_hardship              237       1.0       0.464
third_party_ptp           154       0.0       0.301
rpc_dispute               139       1.0       0.272
rpc_claims_paid           135       1.0       0.264
invalid_number             88       0.0       0.172
language_barrier           44       0.0       0.086

first-pass outcome group

In [63]:
def classify_outcome(disposition):

    if disposition in rpc_dispositions:
        return "RPC"

    elif disposition in [
        "third_party_contact",
        "third_party_ptp"
    ]:
        return "THIRD_PARTY"

    elif disposition in [
        "wrong_number",
        "invalid_number"
    ]:
        return "INVALID"

    elif disposition in [
        "no_answer",
        "call_rejected",
        "not_reachable",
        "switched_off"
    ]:
        return "UNRESOLVED"

    elif disposition == "language_barrier":
        return "OTHER"

    else:
        return "OTHER"


df_dial_attempts["outcome_group"] = (
    df_dial_attempts["disposition"]
    .apply(classify_outcome)
)

print(
    df_dial_attempts["outcome_group"]
    .value_counts()
)

print(
    df_dial_attempts["outcome_group"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

outcome_group
UNRESOLVED     37690
RPC             8400
THIRD_PARTY     3691
INVALID         1280
OTHER             44
Name: count, dtype: int64
outcome_group
UNRESOLVED     73.75
RPC            16.44
THIRD_PARTY     7.22
INVALID         2.50
OTHER           0.09
Name: proportion, dtype: float64

repeated behaviour of individual phones

In [64]:
phone_history = (
    df_dial_attempts
    .groupby("phone_id")
    .agg(
        attempts=("attempt_id", "count"),
        rpc_count=("is_rpc", "sum"),
        third_party_count=(
            "outcome_group",
            lambda x: (x == "THIRD_PARTY").sum()
        ),
        invalid_count=(
            "outcome_group",
            lambda x: (x == "INVALID").sum()
        ),
        unresolved_count=(
            "outcome_group",
            lambda x: (x == "UNRESOLVED").sum()
        )
    )
)

phone_history["rpc_rate"] = (
    phone_history["rpc_count"]
    / phone_history["attempts"]
)

phone_history["third_party_rate"] = (
    phone_history["third_party_count"]
    / phone_history["attempts"]
)

phone_history["invalid_rate"] = (
    phone_history["invalid_count"]
    / phone_history["attempts"]
)

phone_history["unresolved_rate"] = (
    phone_history["unresolved_count"]
    / phone_history["attempts"]
)

print(phone_history.describe().round(3))

       attempts  rpc_count  third_party_count  invalid_count  \
count  4008.000   4008.000           4008.000       4008.000
mean     12.751      2.096              0.921          0.319
std       8.606      2.640              2.028          0.653
min       1.000      0.000              0.000          0.000
25%       7.000      0.000              0.000          0.000
50%      10.000      1.000              0.000          0.000
75%      18.000      3.000              1.000          0.000
max      57.000     16.000             20.000          3.000

       unresolved_count  rpc_rate  third_party_rate  invalid_rate  \
count          4008.000  4008.000          4008.000      4008.000
mean              9.404     0.167             0.082         0.057
std               7.097     0.206             0.169         0.170
min               0.000     0.000             0.000         0.000
25%               4.000     0.000             0.000         0.000
50%               8.000     0.111             0.000         0.000
75%              13.000     0.262             0.062         0.000
max              47.000     1.000             1.000         1.000

       unresolved_rate
count         4008.000
mean             0.693
std              0.251
min              0.000
25%              0.562
50%              0.731
75%              0.875
max              1.000

suspicious phones

In [65]:
suspicious_phones = phone_history[
    (phone_history["third_party_rate"] > 0) |
    (phone_history["invalid_rate"] > 0)
].sort_values(
    ["third_party_rate", "invalid_rate"],
    ascending=False
)

print("Phones with third-party or invalid evidence:")
print(len(suspicious_phones))

print(
    suspicious_phones.head(30)
)

Phones with third-party or invalid evidence:
1744
          attempts  rpc_count  third_party_count  invalid_count  \
phone_id
PH000391         5          0                  5              0
PH000784         2          0                  2              0
PH000830         1          0                  1              0
PH001530         2          0                  2              0
PH001646         2          0                  2              0
PH002097         1          0                  1              0
PH002144         2          0                  2              0
PH002510         1          0                  1              0
PH002628         1          0                  1              0
PH002725         2          0                  2              0
PH002915         2          0                  2              0
PH003798         1          0                  1              0
PH004533         1          0                  1              0
PH004899         1          0                  1              0
PH004909         1          0                  1              0
PH005701         3          0                  3              0
PH000200         8          0                  7              0
PH002547         8          0                  7              0
PH002533         7          0                  6              1
PH002023         6          0                  5              0
PH000473         5          0                  4              0
PH003459        10          0                  8              0
PH005052         8          0                  6              1
PH000199         8          0                  6              0
PH000235         8          0                  6              0
PH000485         8          0                  6              0
PH000548        12          0                  9              0
PH000577         8          0                  6              0
PH002570         8          0                  6              0
PH004488         8          0                  6              0

          unresolved_count  rpc_rate  third_party_rate  invalid_rate  \
phone_id
PH000391                 0       0.0          1.000000      0.000000
PH000784                 0       0.0          1.000000      0.000000
PH000830                 0       0.0          1.000000      0.000000
PH001530                 0       0.0          1.000000      0.000000
PH001646                 0       0.0          1.000000      0.000000
PH002097                 0       0.0          1.000000      0.000000
PH002144                 0       0.0          1.000000      0.000000
PH002510                 0       0.0          1.000000      0.000000
PH002628                 0       0.0          1.000000      0.000000
PH002725                 0       0.0          1.000000      0.000000
PH002915                 0       0.0          1.000000      0.000000
PH003798                 0       0.0          1.000000      0.000000
PH004533                 0       0.0          1.000000      0.000000
PH004899                 0       0.0          1.000000      0.000000
PH004909                 0       0.0          1.000000      0.000000
PH005701                 0       0.0          1.000000      0.000000
PH000200                 1       0.0          0.875000      0.000000
PH002547                 1       0.0          0.875000      0.000000
PH002533                 0       0.0          0.857143      0.142857
PH002023                 1       0.0          0.833333      0.000000
PH000473                 1       0.0          0.800000      0.000000
PH003459                 2       0.0          0.800000      0.000000
PH005052                 1       0.0          0.750000      0.125000
PH000199                 2       0.0          0.750000      0.000000
PH000235                 2       0.0          0.750000      0.000000
PH000485                 2       0.0          0.750000      0.000000
PH000548                 3       0.0          0.750000      0.000000
PH000577                 2       0.0          0.750000      0.000000
PH002570                 2       0.0          0.750000      0.000000
PH004488                 2       0.0          0.750000      0.000000

          unresolved_rate
phone_id
PH000391         0.000000
PH000784         0.000000
PH000830         0.000000
PH001530         0.000000
PH001646         0.000000
PH002097         0.000000
PH002144         0.000000
PH002510         0.000000
PH002628         0.000000
PH002725         0.000000
PH002915         0.000000
PH003798         0.000000
PH004533         0.000000
PH004899         0.000000
PH004909         0.000000
PH005701         0.000000
PH000200         0.125000
PH002547         0.125000
PH002533         0.000000
PH002023         0.166667
PH000473         0.200000
PH003459         0.200000
PH005052         0.125000
PH000199         0.250000
PH000235         0.250000
PH000485         0.250000
PH000548         0.250000
PH000577         0.250000
PH002570         0.250000
PH004488         0.250000

In [66]:
verified_analysis = (
    df_verified_contact_point
    .merge(
        phone_history,
        on="phone_id",
        how="left"
    )
)

print(
    verified_analysis[
        [
            "verified_status",
            "attempts",
            "rpc_rate",
            "third_party_rate",
            "invalid_rate",
            "unresolved_rate"
        ]
    ]
    .groupby("verified_status")
    .agg(
        count=("verified_status", "size"),
        median_attempts=("attempts", "median"),
        median_rpc_rate=("rpc_rate", "median"),
        median_third_party_rate=("third_party_rate", "median"),
        median_invalid_rate=("invalid_rate", "median"),
        median_unresolved_rate=("unresolved_rate", "median")
    )
    .round(3)
)

                     count  median_attempts  median_rpc_rate  \
verified_status
borrower_number        127             12.0            0.217
invalid_number           3              2.0            0.000
not_borrower_number     27              8.0            0.000
switched_off            19              8.0            0.000
third_party_number      74              8.0            0.000

                     median_third_party_rate  median_invalid_rate  \
verified_status
borrower_number                        0.000                0.000
invalid_number                         0.000                1.000
not_borrower_number                    0.000                0.188
switched_off                           0.000                0.000
third_party_number                     0.323                0.000

                     median_unresolved_rate
verified_status
borrower_number                       0.750
invalid_number                        0.000
not_borrower_number                   0.690
switched_off                          1.000
third_party_number                    0.604

In [67]:
random_only = df_dial_attempts[
    df_dial_attempts["dialling_arm"] == "random_contact_point"
].copy()

rule_only = df_dial_attempts[
    df_dial_attempts["dialling_arm"] == "rule_based"
].copy()

print("Random arm:")
print(
    random_only["outcome_group"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print("\nRule-based arm:")
print(
    rule_only["outcome_group"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

Random arm:
outcome_group
UNRESOLVED     70.35
RPC            13.45
THIRD_PARTY    12.73
INVALID         3.33
OTHER           0.14
Name: proportion, dtype: float64

Rule-based arm:
outcome_group
UNRESOLVED     73.94
RPC            16.61
THIRD_PARTY     6.91
INVALID         2.46
OTHER           0.08
Name: proportion, dtype: float64

In [68]:
phone_arm = pd.crosstab(
    df_dial_attempts["phone_id"],
    df_dial_attempts["dialling_arm"]
)

phone_arm["total"] = phone_arm.sum(axis=1)

phone_arm["random_fraction"] = (
    phone_arm.get("random_contact_point", 0)
    / phone_arm["total"]
)

print(phone_arm["random_fraction"].describe())

print(
    "\nPhones receiving at least one random exploration attempt:",
    (phone_arm.get("random_contact_point", 0) > 0).sum()
)

count    4008.000000
mean        0.063569
std         0.243810
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000
Name: random_fraction, dtype: float64

Phones receiving at least one random exploration attempt: 256

In [69]:
phone_dates = (
    df_dial_attempts
    .groupby("phone_id")
    .agg(
        first_attempt=("attempt_ts", "min"),
        last_attempt=("attempt_ts", "max"),
        attempts=("attempt_id", "count")
    )
)

phone_dates["active_days"] = (
    phone_dates["last_attempt"]
    - phone_dates["first_attempt"]
).dt.total_seconds() / (24 * 3600)

print(phone_dates.describe().round(2))

                    first_attempt                last_attempt  attempts  \
count                        4008                        4008   4008.00
mean   2026-04-18 01:46:23.967565  2026-05-27 16:09:06.757984     12.75
min           2026-04-01 08:01:00         2026-04-01 08:09:32      1.00
25%    2026-04-02 11:28:29.250000  2026-05-02 11:56:00.500000      7.00
50%           2026-04-06 12:46:25  2026-06-03 11:05:38.500000     10.00
75%           2026-04-28 11:21:16  2026-06-24 09:45:23.750000     18.00
max           2026-06-29 15:26:06         2026-06-29 18:54:35     57.00
std                           NaN                         NaN      8.61

       active_days
count      4008.00
mean         39.60
min           0.00
25%          14.34
50%          34.34
75%          65.85
max          89.39
std          28.26

In [70]:
df_sorted = df_dial_attempts.sort_values(
    ["phone_id", "attempt_ts"]
).copy()

df_sorted["previous_rpc_count"] = (
    df_sorted
    .groupby("phone_id")["is_rpc"]
    .cumsum()
    .shift(fill_value=0)
)

df_sorted["previous_attempt_count"] = (
    df_sorted
    .groupby("phone_id")
    .cumcount()
)

rpc_rows = df_sorted[df_sorted["is_rpc"]]

print(
    rpc_rows[
        ["previous_attempt_count", "previous_rpc_count"]
    ]
    .describe()
)

       previous_attempt_count  previous_rpc_count
count              8400.00000         8400.000000
mean                  9.29250            2.378929
std                   7.78658            2.425822
min                   0.00000            0.000000
25%                   3.00000            1.000000
50%                   7.00000            2.000000
75%                  14.00000            4.000000
max                  52.00000           15.000000

adding new feature to the dataset

In [71]:
attempts = df_dial_attempts.copy()

attempts["attempt_ts"] = pd.to_datetime(
    attempts["attempt_ts"],
    errors="coerce"
)

attempts = attempts.sort_values(
    ["account_id", "phone_id", "attempt_ts"]
).reset_index(drop=True)

# This is the actual contact point being tested
attempts["contact_point_key"] = (
    attempts["account_id"].astype(str)
    + "_"
    + attempts["phone_id"].astype(str)
)

# Primary outcome
attempts["is_rpc"] = (
    attempts["disposition"]
    .astype(str)
    .str.startswith("rpc_")
)

# Safety / invalid-contact outcome
attempts["is_unsafe"] = attempts["disposition"].isin([
    "third_party_contact",
    "third_party_ptp",
    "wrong_number",
    "invalid_number"
])

print("Rows:", len(attempts))
print("RPC:", attempts["is_rpc"].sum())
print("Unsafe:", attempts["is_unsafe"].sum())

print("\nRPC rate:")
print(attempts["is_rpc"].mean())

print("\nUnsafe rate:")
print(attempts["is_unsafe"].mean())

Rows: 51105
RPC: 8400
Unsafe: 4971

RPC rate:
0.16436747872028176

Unsafe rate:
0.09727032579982389

In [73]:
attempts.head(5)

,attempt_id,account_id,phone_id,attempt_ts,channel,agent_id,dialling_arm,selection_propensity,network_response,ring_duration_s,...,hangup_by,disposition,remark,ptp_id,has_transcript,attempt_hour,is_rpc,outcome_group,contact_point_key,is_unsafe
0,AT0002606,AC000001,PH000611,2026-04-04 09:14:39,tele_agent,TA006,rule_based,1.0,switched_off,0,...,network,switched_off,phone band hai,NaN,False,9,False,UNRESOLVED,AC000001_PH000611,False
1,AT0003277,AC000001,PH000611,2026-04-04 14:57:03,tele_agent,TA006,rule_based,1.0,not_reachable,0,...,network,not_reachable,not reachable,NaN,False,14,False,UNRESOLVED,AC000001_PH000611,False
2,AT0004587,AC000001,PH000611,2026-04-07 12:38:03,tele_agent,TA006,rule_based,1.0,not_reachable,0,...,network,not_reachable,out of coverage,NaN,False,12,False,UNRESOLVED,AC000001_PH000611,False
3,AT0005428,AC000001,PH000611,2026-04-08 08:01:51,tele_agent,TA006,rule_based,1.0,not_reachable,0,...,network,not_reachable,network nahi hai,NaN,False,8,False,UNRESOLVED,AC000001_PH000611,False
4,AT0006218,AC000001,PH000611,2026-04-09 12:25:47,tele_agent,TA006,rule_based,1.0,not_reachable,0,...,network,not_reachable,not reachalbe,NaN,False,12,False,UNRESOLVED,AC000001_PH000611,False

In [74]:
g = attempts.groupby(
    "contact_point_key",
    sort=False
)

# Number of attempts BEFORE the current attempt
attempts["prior_attempts"] = (
    g.cumcount()
)

# Number of previous RPCs
attempts["prior_rpc"] = (
    g["is_rpc"].cumsum()
    - attempts["is_rpc"].astype(int)
)

# Number of previous unsafe outcomes
attempts["prior_unsafe"] = (
    g["is_unsafe"].cumsum()
    - attempts["is_unsafe"].astype(int)
)

# Historical rates
attempts["prior_rpc_rate"] = np.where(
    attempts["prior_attempts"] > 0,
    attempts["prior_rpc"] / attempts["prior_attempts"],
    0.0
)

attempts["prior_unsafe_rate"] = np.where(
    attempts["prior_attempts"] > 0,
    attempts["prior_unsafe"] / attempts["prior_attempts"],
    0.0
)

print(
    attempts[
        [
            "contact_point_key",
            "attempt_ts",
            "prior_attempts",
            "prior_rpc",
            "prior_unsafe",
            "prior_rpc_rate",
            "prior_unsafe_rate"
        ]
    ].head(20)
)

    contact_point_key          attempt_ts  prior_attempts  prior_rpc  \
0   AC000001_PH000611 2026-04-04 09:14:39               0          0
1   AC000001_PH000611 2026-04-04 14:57:03               1          0
2   AC000001_PH000611 2026-04-07 12:38:03               2          0
3   AC000001_PH000611 2026-04-08 08:01:51               3          0
4   AC000001_PH000611 2026-04-09 12:25:47               4          0
5   AC000001_PH000611 2026-04-09 17:20:45               5          0
6   AC000001_PH000611 2026-04-13 09:51:15               6          0
7   AC000001_PH000611 2026-04-18 12:23:40               7          0
8   AC000001_PH000612 2026-04-18 18:22:53               0          0
9   AC000001_PH000612 2026-04-20 08:10:15               1          0
10  AC000001_PH000612 2026-04-27 08:30:25               2          0
11  AC000001_PH000612 2026-04-28 12:22:36               3          0
12  AC000001_PH000612 2026-05-04 08:20:38               4          0
13  AC000001_PH000612 2026-05-07 10:08:29               5          0
14  AC000001_PH000612 2026-05-13 11:58:13               6          0
15  AC000002_PH000613 2026-04-02 10:55:33               0          0
16  AC000003_PH000615 2026-04-01 09:48:09               0          0
17  AC000003_PH000615 2026-04-01 15:46:54               1          0
18  AC000003_PH000615 2026-04-02 10:34:37               2          0
19  AC000003_PH000615 2026-04-02 17:58:13               3          0

    prior_unsafe  prior_rpc_rate  prior_unsafe_rate
0              0             0.0           0.000000
1              0             0.0           0.000000
2              0             0.0           0.000000
3              0             0.0           0.000000
4              0             0.0           0.000000
5              0             0.0           0.000000
6              0             0.0           0.000000
7              0             0.0           0.000000
8              0             0.0           0.000000
9              1             0.0           1.000000
10             1             0.0           0.500000
11             1             0.0           0.333333
12             1             0.0           0.250000
13             2             0.0           0.400000
14             3             0.0           0.500000
15             0             0.0           0.000000
16             0             0.0           0.000000
17             0             0.0           0.000000
18             0             0.0           0.000000
19             0             0.0           0.000000

In [75]:
attempts["previous_disposition"] = (
    g["disposition"].shift(1)
)

attempts["previous_network_response"] = (
    g["network_response"].shift(1)
)

attempts["previous_hangup_by"] = (
    g["hangup_by"].shift(1)
)

attempts["previous_attempt_ts"] = (
    g["attempt_ts"].shift(1)
)

attempts["days_since_previous_attempt"] = (
    attempts["attempt_ts"]
    - attempts["previous_attempt_ts"]
).dt.total_seconds() / (24 * 3600)

attempts["days_since_previous_attempt"] = (
    attempts["days_since_previous_attempt"]
    .fillna(-1)
)

print(
    attempts[
        [
            "contact_point_key",
            "attempt_ts",
            "previous_disposition",
            "previous_network_response",
            "days_since_previous_attempt"
        ]
    ].head(20)
)

    contact_point_key          attempt_ts previous_disposition  \
0   AC000001_PH000611 2026-04-04 09:14:39                  NaN
1   AC000001_PH000611 2026-04-04 14:57:03         switched_off
2   AC000001_PH000611 2026-04-07 12:38:03        not_reachable
3   AC000001_PH000611 2026-04-08 08:01:51        not_reachable
4   AC000001_PH000611 2026-04-09 12:25:47        not_reachable
5   AC000001_PH000611 2026-04-09 17:20:45        not_reachable
6   AC000001_PH000611 2026-04-13 09:51:15         switched_off
7   AC000001_PH000611 2026-04-18 12:23:40        not_reachable
8   AC000001_PH000612 2026-04-18 18:22:53                  NaN
9   AC000001_PH000612 2026-04-20 08:10:15  third_party_contact
10  AC000001_PH000612 2026-04-27 08:30:25            no_answer
11  AC000001_PH000612 2026-04-28 12:22:36            no_answer
12  AC000001_PH000612 2026-05-04 08:20:38        call_rejected
13  AC000001_PH000612 2026-05-07 10:08:29         wrong_number
14  AC000001_PH000612 2026-05-13 11:58:13  third_party_contact
15  AC000002_PH000613 2026-04-02 10:55:33                  NaN
16  AC000003_PH000615 2026-04-01 09:48:09                  NaN
17  AC000003_PH000615 2026-04-01 15:46:54            no_answer
18  AC000003_PH000615 2026-04-02 10:34:37            no_answer
19  AC000003_PH000615 2026-04-02 17:58:13            no_answer

   previous_network_response  days_since_previous_attempt
0                        NaN                    -1.000000
1               switched_off                     0.237778
2              not_reachable                     2.903472
3              not_reachable                     0.808194
4              not_reachable                     1.183287
5              not_reachable                     0.204838
6               switched_off                     3.687847
7              not_reachable                     5.105845
8                        NaN                    -1.000000
9                   answered                     1.574560
10            ring_no_answer                     7.014005
11            ring_no_answer                     1.161238
12             busy_rejected                     5.831968
13                  answered                     3.074896
14                  answered                     6.076204
15                       NaN                    -1.000000
16                       NaN                    -1.000000
17            ring_no_answer                     0.249132
18            ring_no_answer                     0.783137
19            ring_no_answer                     0.308056

TIME feature

In [76]:
attempts["attempt_hour"] = (
    attempts["attempt_ts"].dt.hour
)

attempts["day_of_week"] = (
    attempts["attempt_ts"].dt.dayofweek
)

attempts["is_weekend"] = (
    attempts["day_of_week"] >= 5
).astype(int)

add phone information

In [77]:
phone_features = df_phone.copy()

phone_features["added_date"] = pd.to_datetime(
    phone_features["added_date"],
    errors="coerce"
)

# How many accounts share this phone?
shared_phone_count = (
    phone_features
    .groupby("phone_id")["account_id"]
    .nunique()
    .rename("phone_account_count")
    .reset_index()
)

phone_features = phone_features.merge(
    shared_phone_count,
    on="phone_id",
    how="left"
)

attempts = attempts.merge(
    phone_features[
        [
            "phone_id",
            "source",
            "relation_recorded",
            "added_date",
            "priority_slot",
            "phone_account_count"
        ]
    ],
    on="phone_id",
    how="left"
)

attempts["phone_age_days"] = (
    attempts["attempt_ts"]
    - attempts["added_date"]
).dt.total_seconds() / (24 * 3600)

print(
    attempts[
        [
            "phone_id",
            "source",
            "relation_recorded",
            "priority_slot",
            "phone_account_count",
            "phone_age_days"
        ]
    ].head()
)

   phone_id           source relation_recorded  priority_slot  \
0  PH000611  kyc_origination              self              0
1  PH000611  kyc_origination              self              0
2  PH000611  kyc_origination              self              0
3  PH000611  kyc_origination              self              0
4  PH000611  kyc_origination              self              0

   phone_account_count  phone_age_days
0                    1        3.385174
1                    1        3.622951
2                    1        6.526424
3                    1        7.334618
4                    1        8.517905

account information

In [78]:
account_features = df_accounts.copy()

attempts = attempts.merge(
    account_features,
    on="account_id",
    how="left",
    suffixes=("", "_account")
)

print(attempts.shape)
print(attempts.columns.tolist())

(52367, 58)
['attempt_id', 'account_id', 'phone_id', 'attempt_ts', 'channel', 'agent_id', 'dialling_arm', 'selection_propensity', 'network_response', 'ring_duration_s', 'talk_duration_s', 'hangup_by', 'disposition', 'remark', 'ptp_id', 'has_transcript', 'attempt_hour', 'is_rpc', 'outcome_group', 'contact_point_key', 'is_unsafe', 'prior_attempts', 'prior_rpc', 'prior_unsafe', 'prior_rpc_rate', 'prior_unsafe_rate', 'previous_disposition', 'previous_network_response', 'previous_hangup_by', 'previous_attempt_ts', 'days_since_previous_attempt', 'day_of_week', 'is_weekend', 'source', 'relation_recorded', 'added_date', 'priority_slot', 'phone_account_count', 'phone_age_days', 'lender_id', 'portfolio', 'income_type', 'town_id', 'preferred_language', 'bucket_start', 'dpd_start', 'emi_amount', 'overdue_start', 'outstanding', 'salary_credit_day', 'bureau_score_band', 'other_active_loans', 'paid_other_lenders_30d', 'last_bounce_reason', 'ability_to_pay_estimate', 'prev_ptp_count', 'prev_ptp_broken', 'dialling_arm_account']

NEW ATTEM TABLE

In [90]:
model_attempts = df_dial_attempts.copy()

model_attempts["attempt_ts"] = pd.to_datetime(
    model_attempts["attempt_ts"],
    errors="coerce"
)

model_attempts = (
    model_attempts
    .sort_values(["account_id", "phone_id", "attempt_ts"])
    .reset_index(drop=True)
)

model_attempts["contact_point_key"] = (
    model_attempts["account_id"].astype(str)
    + "_"
    + model_attempts["phone_id"].astype(str)
)

print("Original attempts:", len(df_dial_attempts))
print("Model attempts:", len(model_attempts))

assert len(model_attempts) == len(df_dial_attempts)

print("Row count check: PASSED")

Original attempts: 51105
Model attempts: 51105
Row count check: PASSED

In [91]:
rpc_dispositions = [
    "rpc_ptp",
    "rpc_hung_up",
    "rpc_call_back",
    "rpc_refused",
    "rpc_hardship",
    "rpc_dispute",
    "rpc_claims_paid"
]

third_party_dispositions = [
    "third_party_contact",
    "third_party_ptp"
]

invalid_dispositions = [
    "wrong_number",
    "invalid_number"
]

model_attempts["target_rpc"] = (
    model_attempts["disposition"]
    .isin(rpc_dispositions)
).astype(int)

model_attempts["target_third_party"] = (
    model_attempts["disposition"]
    .isin(third_party_dispositions)
).astype(int)

model_attempts["target_invalid"] = (
    model_attempts["disposition"]
    .isin(invalid_dispositions)
).astype(int)

print("RPC:", model_attempts["target_rpc"].sum())
print("Third party:", model_attempts["target_third_party"].sum())
print("Invalid:", model_attempts["target_invalid"].sum())

RPC: 8400
Third party: 3691
Invalid: 1280

In [92]:
rpc_dispositions = [
    "rpc_ptp",
    "rpc_hung_up",
    "rpc_call_back",
    "rpc_refused",
    "rpc_hardship",
    "rpc_dispute",
    "rpc_claims_paid"
]

third_party_dispositions = [
    "third_party_contact",
    "third_party_ptp"
]

invalid_dispositions = [
    "wrong_number",
    "invalid_number"
]

model_attempts["target_rpc"] = (
    model_attempts["disposition"]
    .isin(rpc_dispositions)
).astype(int)

model_attempts["target_third_party"] = (
    model_attempts["disposition"]
    .isin(third_party_dispositions)
).astype(int)

model_attempts["target_invalid"] = (
    model_attempts["disposition"]
    .isin(invalid_dispositions)
).astype(int)

print("RPC:", model_attempts["target_rpc"].sum())
print("Third party:", model_attempts["target_third_party"].sum())
print("Invalid:", model_attempts["target_invalid"].sum())

RPC: 8400
Third party: 3691
Invalid: 1280

In [93]:
model_attempts["previous_disposition"] = (
    g["disposition"].shift(1)
)

model_attempts["previous_network_response"] = (
    g["network_response"].shift(1)
)

model_attempts["previous_hangup_by"] = (
    g["hangup_by"].shift(1)
)

model_attempts["previous_attempt_ts"] = (
    g["attempt_ts"].shift(1)
)

model_attempts["days_since_previous_attempt"] = (
    model_attempts["attempt_ts"]
    - model_attempts["previous_attempt_ts"]
).dt.total_seconds() / 86400

model_attempts["days_since_previous_attempt"] = (
    model_attempts["days_since_previous_attempt"]
    .fillna(-1)
)

In [94]:
model_attempts["attempt_hour"] = (
    model_attempts["attempt_ts"].dt.hour
)

model_attempts["day_of_week"] = (
    model_attempts["attempt_ts"].dt.dayofweek
)

model_attempts["is_weekend"] = (
    model_attempts["day_of_week"] >= 5
).astype(int)

In [95]:
phone_features = df_phone.copy()

phone_features["added_date"] = pd.to_datetime(
    phone_features["added_date"],
    errors="coerce"
)

phone_features = phone_features[
    [
        "account_id",
        "phone_id",
        "source",
        "relation_recorded",
        "added_date",
        "priority_slot"
    ]
]

model_attempts = model_attempts.merge(
    phone_features,
    on=["account_id", "phone_id"],
    how="left",
    validate="many_to_one"
)

assert len(model_attempts) == len(df_dial_attempts)

print("Phone merge row count:", len(model_attempts))
print("Phone merge: PASSED")

Phone merge row count: 51105
Phone merge: PASSED